import { load, dump } from "js-yaml";

/**
 * Policy model — a faithful TypeScript port of `crates/kriya/src/permissions.rs`.
 *
 * The host evaluates rules top-to-bottom; the FIRST matching rule wins, and no match
 * means Deny (deny-by-default). A rule maps an action pattern to a tier:
 *   - allow                → `allow: true`
 *   - require human approval → `allow: true, require_approval: true`
 *   - deny                 → `allow: false`
 * The console edits this model and emits the same YAML the host loads.
 */

export type Tier = "allow" | "approval" | "deny";

export interface PolicyRule {
  /** Exact action id, a `prefix_*` glob, or `*` for all. Order matters (first match wins). */
  action: string;
  tier: Tier;
}

export interface Policy {
  rules: PolicyRule[];
  /** Max actions per trailing 60s window. `null` = no cap. */
  maxActionsPerMinute: number | null;
}

// ── YAML shapes (what the host's serde sees) ──────────────────────────────────
interface YamlRule {
  action: string;
  allow?: boolean;
  require_approval?: boolean;
}
interface YamlPolicy {
  rules?: YamlRule[];
  budget?: { max_actions_per_minute?: number | null };
}

export function tierFrom(allow: boolean, requireApproval: boolean): Tier {
  if (!allow) return "deny";
  return requireApproval ? "approval" : "allow";
}

export const TIER_LABEL: Record<Tier, string> = {
  allow: "Allow",
  approval: "Require approval",
  deny: "Deny",
};

/** The host's built-in default when no policy file is present (`Policy::default`). */
export function defaultPolicy(): Policy {
  return {
    rules: [
      { action: "create_*", tier: "allow" },
      { action: "edit_*", tier: "allow" },
      { action: "delete_*", tier: "approval" },
      { action: "*", tier: "deny" },
    ],
    maxActionsPerMinute: 60,
  };
}

export function parsePolicyYaml(text: string): Policy {
  const doc = (load(text) ?? {}) as YamlPolicy;
  const rules = Array.isArray(doc.rules) ? doc.rules : [];
  return {
    rules: rules
      .filter((r): r is YamlRule => !!r && typeof r.action === "string")
      .map((r) => ({ action: r.action, tier: tierFrom(Boolean(r.allow), Boolean(r.require_approval)) })),
    maxActionsPerMinute:
      doc.budget && typeof doc.budget.max_actions_per_minute === "number"
        ? doc.budget.max_actions_per_minute
        : null,
  };
}

const YAML_HEADER = `# kriya governance policy — generated by kriya Console.
# The host (kriya / kriya-mcp) enforces this on every agent action: rules are
# evaluated top-to-bottom, the first match wins, and no match = deny.
`;

export function policyToYaml(p: Policy): string {
  const rules: YamlRule[] = p.rules.map((r) => {
    const o: YamlRule = { action: r.action, allow: r.tier !== "deny" };
    if (r.tier === "approval") o.require_approval = true;
    return o;
  });
  const doc: YamlPolicy = { rules };
  if (p.maxActionsPerMinute !== null) doc.budget = { max_actions_per_minute: p.maxActionsPerMinute };
  const body = dump(doc, { lineWidth: -1, quotingType: '"', forceQuotes: true });
  return YAML_HEADER + body;
}

// ── matching + decision (port of `matches` / `check`) ─────────────────────────
export function matchesPattern(pattern: string, actionId: string): boolean {
  if (pattern === "*") return true;
  if (pattern.endsWith("*")) return actionId.startsWith(pattern.slice(0, -1));
  return pattern === actionId;
}

export interface DecisionResult {
  decision: Tier; // reuse Tier as the decision space (allow | approval | deny)
  matchedIndex: number | null; // null = fell through to implicit deny
}

export function decide(policy: Policy, actionId: string): DecisionResult {
  for (let i = 0; i < policy.rules.length; i++) {
    const rule = policy.rules[i]!;
    if (matchesPattern(rule.action, actionId)) {
      return { decision: rule.tier, matchedIndex: i };
    }
  }
  return { decision: "deny", matchedIndex: null };
}

// ── lint (port of `Policy::warnings`) ─────────────────────────────────────────
const DESTRUCTIVE_KEYWORDS = ["delete", "remove", "destroy", "drop", "purge", "wipe"];

function isDestructiveName(pattern: string): boolean {
  const p = pattern.toLowerCase();
  return DESTRUCTIVE_KEYWORDS.some((k) => p.includes(k));
}

export type LintSeverity = "high" | "medium";

export interface LintWarning {
  severity: LintSeverity;
  message: string;
  ruleIndex: number | null;
}

export function lintPolicy(policy: Policy): LintWarning[] {
  const out: LintWarning[] = [];
  const destructive: LintWarning[] = [];

  policy.rules.forEach((rule, i) => {
    const allow = rule.tier !== "deny";
    const requireApproval = rule.tier === "approval";

    if (allow && !requireApproval && isDestructiveName(rule.action)) {
      destructive.push({
        severity: "high",
        ruleIndex: i,
        message: `Rule ${i + 1}: "${rule.action}" is allowed without human approval — destructive-sounding actions usually want approval.`,
      });
    }
    if (rule.action === "*" && allow && !requireApproval) {
      out.push({
        severity: "high",
        ruleIndex: i,
        message: `Rule ${i + 1}: catch-all "*" allows every action without approval — this defeats the deny-by-default model.`,
      });
    }
  });

  out.push(...destructive);

  if (!policy.rules.some((r) => r.action === "*")) {
    out.push({
      severity: "medium",
      ruleIndex: null,
      message: `No explicit catch-all "*" rule — the host falls through to deny, but an explicit "*" → Deny makes the intent obvious.`,
    });
  }
  if (policy.maxActionsPerMinute === null) {
    out.push({
      severity: "medium",
      ruleIndex: null,
      message: `No per-minute budget cap — an agent stuck in a loop can hammer your app indefinitely. Recommend a cap (e.g. 60).`,
    });
  }

  return out;
}
