// The committed NIST 800-171 AU-family sample pack (R1-1's C3PAO template-(c) leave-behind,
// generated by scripts/gen-au-sample.mts) must stay PII-free and reflect a genuinely verified
// trail — this is a leave-behind attached to real outreach, so both properties are load-bearing.
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sampleDir = join(root, "docs/gtm/samples/au-family-sample");
const PII = /\b(alice|bob|carol)\b|@/i;

describe("AU-family sample pack (docs/gtm/samples/au-family-sample)", () => {
  it("evidence.json is PII-free and has at least one verified receipt", () => {
    const text = readFileSync(join(sampleDir, "evidence.json"), "utf8");
    expect(text).not.toMatch(PII);
    const bundle = JSON.parse(text);
    expect(bundle.integrity.verified).toBeGreaterThanOrEqual(1);
    expect(bundle.controls.filter((c: { framework: string }) => c.framework === "NIST 800-171").length).toBe(9);
  });

  it("evidence.md is PII-free and contains no certified/compliant claims", () => {
    const text = readFileSync(join(sampleDir, "evidence.md"), "utf8");
    expect(text).not.toMatch(PII);
    expect(text).not.toMatch(/\bcertified\b|\bcompliant\b/i);
    expect(text).toContain("evidence, not a certification");
  });
});
