// Clean, PII-free, genuinely Ed25519-signed dataset for marketing screenshots (generated by
// demo/capture/gen-capture-data.mjs). Imported ONLY in a `__KRIYA_DEMO__` capture build (?capture=1),
// so — like the demo seed — it is tree-shaken out of the shipped desktop app.
import captureAudit from "./capture/capture-audit.jsonl?raw";
import captureApprovals from "./capture/capture-approvals.jsonl?raw";

export const CAPTURE_AUDIT = captureAudit;
export const CAPTURE_APPROVALS = captureApprovals;
